---
title: "PA multiresistance and resistance index"
author: "Governance and socioeconomic  factors contributing to European countries antimicrobial resistance: a data panel and machine-learning analysis"
date: "18/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading packages, echo=FALSE, include=FALSE}
### Carga de librerias ###
devtools::install_github("rstudio/addinexamples", type = "source")
library(dplyr)
library(tidyverse)
library(magrittr)
library(ggplot2)
library(rvest)
library(stringr)
library(imputeTS)
library(factoextra)
library(FactoMineR)
library(GGally)
library(ggpubr)
library(ggplot2)
library(ggfortify)
library(ggcorrplot)
library(dslabs)
library(tseries)
library(ggpubr)

```

```{r creating datasets, echo=FALSE, include=FALSE}

### Loading and bulding datasets for first part (R_index)

Pseudomona_db <- read.csv("~/Dropbox/Kernel-Jhoana/Resistencia-socioeconomico/Scripts/data_complete_int.csv") %>% 
    rename('R_multi' = 'multi_R_perc', 
           'R_index' = 'r_index')

### creating a function that become values above 0 to 0 (because this are frequencies)
min_0 <- function(x){ifelse(x < 0, 0, x)}

### applying function min_0 to every importan resistance variable ###
Pseudomona_db <- Pseudomona_db %>% mutate(across(c("Aminoglycosides", "Carbapenems", "Ceftazidime",
                                    "Fluoroquinolones", "Piperacilina_taz", "R_multi"),
                                  min_0))

### creating chunks of data to further analysis & generating data variables ###
Pseudomona <- Pseudomona_db[, -c(3, 11:12, 14:26)]

p.aeuro_r <- Pseudomona

p.aeuro_r_2 <- cbind(p.aeuro_r, Pseudomona_db$R_index/100) %>% rename("R_index" ="Pseudomona_db$R_index/100")

Data <- as_tibble(Pseudomona[, -c(1:4, 11:12, 14:26)])

n <- nrow(Data) 

### Graphic analysis of resistance variables
gath_p.aeuro <- Pseudomona %>% 
    gather(key = "antibiotic", value = "resistance", 5:10)


data_PA <- read.csv("~/Dropbox/Kernel-Jhoana/Resistencia-socioeconomico/Scripts/data_complete_int.csv")

### setting and recalling a new dataset including only interes variables ###
vars_corr <- data_PA %>% select(r_index, multi_R_perc, DDD_sys_commun, 
                                per_cap_US., GDP_total, GDP_._health, 
                                Out_pocket_exp, HDR, ctrl_corrup, GOV_effect, 
                                rule_law, rural_pop) %>% 
    rename('R_index' = 'r_index',
           'R_multi' = 'multi_R_perc',
           'GDP_Health' = 'GDP_._health', 
           'HDI' = 'HDR')


```

```{r correlations antibiotics, echo=FALSE}
Corr_resist <- round(cor(Data), 2)

### Correlation graph resistance variables
ggcorrplot(Corr_resist, hc.order = TRUE, 
           type = "lower", 
           lab = TRUE, 
           lab_size = 3, 
           method="circle", 
           colors = c("tomato2", "white", "springgreen3"),
           ggtheme=theme_bw, title = "Correlogran of antibiotics resistances")

```

```{r boxplot by region rmulti vs rindex, echo=FALSE}

graph_multi <- p.aeuro_r_2 %>% select(Bacteria, Year, Country, Region, R_multi, R_index) %>% 
    gather(key = "antibiotic", value = "resistance", 5:ncol(.))

### BP by Region R_index and R_multi
graph_multi %>%
    mutate(Region = reorder(Region, resistance, FUN = mean)) %>%      # reorder
    ggplot(aes(Region, resistance, fill = antibiotic)) +    # color by continent
    geom_boxplot() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    ylab("Resistance Log2(%)") +
    xlab("") + 
    geom_jitter(width = 0.1, alpha = 0.1)+
    scale_y_continuous(trans = 'log2', 
                       labels = scales::number_format(accuracy = 0.01)) + 
    ggtitle("Boxplot by Region")+ 
    ds_theme_set(legend.title = element_blank(), legend.position="bottom")

```

```{r BP by Country R_index and R_multi, echo=FALSE}
### BP by Country R_index and R_multi
graph_multi %>%
    mutate(Country = reorder(Country, resistance, FUN = mean)) %>%      # reorder
    ggplot(aes(Country, resistance, fill = antibiotic)) +    # color by antibiotic
    geom_boxplot() +
    ylab("Resistance Log2(%)")+
    xlab("") + #geom_point(show.legend = FALSE) + 
    scale_y_continuous(trans = 'log2', 
                       labels = scales::number_format(accuracy = 0.01)) + 
    ggtitle("Boxplot by country")+ 
    ds_theme_set(legend.title = element_blank(), legend.position="bottom", 
                 axis.text.x = element_text(angle = 90, hjust = 1))
```

```{r mojena test, echo=FALSE, include=FALSE}
mojena = function(hc){
    n_hd = length(hc$height)
    alp_g = 0 ; alpha = hc$height[n_hd:1]
    for(i in 1:(n_hd-1)){
        alp_g[i] = mean(alpha[(n_hd-i+1):1])+1.25*sd(alpha[(n_hd-i+1):1])
        # alp_g[i] = mean(alpha[(n_hd-i+1):1])+3.5*sd(alpha[(n_hd-i+1):1])
    }
    nog = sum(alp_g<= alpha[-n_hd]) + 1
    plot(alpha[-n_hd], pch=20, col=(alp_g>alpha[-n_hd])+1, main = paste("Número óptimo de grupos =",nog),
         ylab = expression(alpha[g]), xlab="Nodos")}

```

```{r heatmap distances antibiotics, echo=FALSE}

attach(Pseudomona_db)
mean_pseudo<- Pseudomona_db %>% group_by(Country) %>%
    summarise(Amino = mean(Aminoglycosides), 
              Carba = mean(Carbapenems), 
              Fluo = mean(Fluoroquinolones), 
              Cefta = mean(Ceftazidime), 
              Piper = mean(Piperacilina_taz))

multi_pseudo <- as_tibble(mean_pseudo[, -1])
rownames(multi_pseudo) <- mean_pseudo$Country

distance<- get_dist(multi_pseudo, stand = TRUE, method = "euclidean") 
fviz_dist(distance, 
          gradient = list(low = "#00AFBB", mid = "white", high = "#FC4E07"))
```

```{r dendogram by average all antibiotics, echo=FALSE}
#Dendograma método de average
average_pseudo= hclust(distance, method = "average")
fviz_dend(average_pseudo, k = 3, # Cortar en 3 grupos
          cex = 0.5, # tama?o de las etiquetas
          k_colors = "npg", # color de los grupos
          color_labels_by_k = TRUE, # color de las etiquetas de los grupos
          rect = TRUE # Agregar un rect?ngulo a los grupos
)
```

```{r clustering and cluster number, echo=FALSE}
#hacemos los cluster
cluster1 <- scale(multi_pseudo)
set.seed(123) ## Semilla
km.res_p.aeruginosa <- kmeans(cluster1, 3,nstart = 25)
cluster2 <- cbind(multi_pseudo, 
                  cluster1=km.res_p.aeruginosa$cluster)

fviz_nbclust(cluster1,kmeans,method = "wss")+
    geom_vline(xintercept = 3, linetype=2) ## Advertencia

```

```{r cluster visualization, echo=FALSE}
## Visualizaci?n conglomerados K-medias
fviz_cluster(km.res_p.aeruginosa, 
             data = cluster1, 
             palette="jco",
             labelsize = 8,
             star.plot= TRUE,
             pointsize = 2,
             repel = TRUE,
             ggtheme=theme_minimal()
)


```

```{r loading database full variables, echo=FALSE, include=FALSE}

data_PA <- read.csv("~/Dropbox/Kernel-Jhoana/Resistencia-socioeconomico/Scripts/data_complete_int.csv")

### setting and recalling a new dataset including only interes variables ###
vars_corr <- data_PA %>% select(r_index, multi_R_perc, DDD_sys_commun, 
                                per_cap_US., GDP_total, GDP_._health, 
                                Out_pocket_exp, HDR, ctrl_corrup, GOV_effect, 
                                rule_law, rural_pop) %>% 
    rename('R_index' = 'r_index',
           'R_multi' = 'multi_R_perc',
           'GDP_Health' = 'GDP_._health', 
           'HDI' = 'HDR')
```

```{r correlations between each variable full dataset, echo=FALSE}
### function of correlation
corr_vars <- round(cor(vars_corr), 2)

### Correlation graph all variables
ggcorrplot(corr_vars, hc.order = TRUE, 
           type = "lower", 
           lab = TRUE, 
           lab_size = 2, 
           method="circle", 
           colors = c("tomato2", "white", "springgreen3"), 
           title="Correlogram of variables", 
           ggtheme=theme_bw)
```

```{r dotplot effects datapanel Rmulti, echo=FALSE}
#### Graph effects country & year, R_multi ###

eff_country <- read.csv2("country_effect_Rmulti.csv") %>% set_colnames(c('Country', 'Effect'))


eff_country_Lv <- eff_country %>% mutate(Effect = as.numeric(as.character(Effect))) %>% 
    mutate(Effect = round(Effect, 2)) %>% 
    mutate(., Effects_level = ifelse(Effect <=0, "Low", "High")) %>% arrange(Effect)

eff_country_Lv$`Country` <- factor(eff_country_Lv$`Country`, levels = eff_country_Lv$`Country`) 
eff_country_Lv$`Effects_level` <- factor(eff_country_Lv$`Effects_level`) 

### DOT PLOT using ggdotchart
require(ggpubr)
ggdot_rmulti <- ggdotchart(eff_country_Lv, x = "Country", y = "Effect",
           color = "Effects_level",                                # Color by groups
           palette = c("#00AFBB","#FC4E07"), # Custom color palett                      # Sort value in descending order
           add = "segments",                           # Add segments from y = 0 to dots
           add.params = list(color = "lightgray", size = 1.5), # Add segments from y = 0 to dots
           rotate = TRUE,                                # Rotate vertically
           group = "Effects_level",                                # Order by groups
           dot.size = 8,                                 # Large dot size
           label = (eff_country_Lv$Effect),                        # Add mpg values as dot labels
           font.label = list(color = "white", size = 7,
                             vjust = 0.5),             # Adjust label parameters
           title = "Dot Plot R_multi by Country",
           subtitle = "Effects per Country in data panel model R_multi",
           caption = "Source: Prepared by the authors", 
           ggtheme = theme_pubr()                        # ggplot2 theme
)

ggdot_rmulti <- ggdot_rmulti +
    font("xlab", size = 12)+
    font("ylab", size = 12)+
    font("xy.text", size = 10)

ggdot_rmulti

```

```{r Graph effects country R_index data panel, echo=FALSE}
#### Graph effects country, R_index ###

eff_index <- read.csv2("country_effect_Rindex.csv") %>% set_colnames(c('Country', 'Effect'))


eff_index_Lv <- eff_index %>% mutate(Effect = as.numeric(as.character(Effect))) %>% 
    mutate(Effect = round(Effect, 2)) %>% 
    mutate(., Effects_level = ifelse(Effect <0, "Low", "High")) %>% arrange(Effect)

eff_index_Lv$`Country` <- factor(eff_country_Lv$`Country`, levels = eff_country_Lv$`Country`) 
eff_index_Lv$`Effects_level` <- factor(eff_country_Lv$`Effects_level`) 

### DOT PLOT using ggdotchart
require(ggpubr)
ggdot_rindex <- ggdotchart(eff_index_Lv, x = "Country", y = "Effect",
           color = "Effects_level",                                # Color by groups
           palette = c("#00AFBB","#FC4E07"), # Custom color palett
           #sorting = "ascending",                        # Sort value in descending order
           add = "segments",                           # Add segments from y = 0 to dots
           add.params = list(color = "lightgray", size = 1.5), # Add segments from y = 0 to dots
           rotate = TRUE,                                # Rotate vertically
           group = "Effects_level",                                # Order by groups
           dot.size = 8,                                 # Large dot size
           label = (eff_index_Lv$Effect),                        # Add mpg values as dot labels
           font.label = list(color = "white", size = 7,
                             vjust = 0.5),# Adjust label parameters
           title = "Dot Plot R_index by Country",
           subtitle = "Effects per Country in data panel model R_index",
           caption = "Source: Prepared by the authors",
           ggtheme = theme_pubr()# ggplot2 theme
)

ggdot_rindex <- ggdot_rindex +
    font("xlab", size = 12)+
    font("ylab", size = 12)+
    font("xy.text", size = 10)

ggdot_rindex

```

